name: workflow3

on: 
  push:
    branches:
      - main

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 10
  test:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 10    
  test2:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 10
  build2:
     runs-on: ubuntu-latest
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 10    
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 10
     needs: test
