name: workflow3

on: 
  push:
    branches:
      - main

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: step1
         # continue-on-error: true
         run: |
           eho "test step 1"
           sleep 5
       - name: step2
         run: |
           echo "test step 2"
           sleep 5
  test:
     runs-on: ubuntu-latest
     needs: [build, build2]
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 5    
  test2:
     runs-on: ubuntu-latest
     needs: [build, build2]
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 5
  build2:
     runs-on: ubuntu-latest
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 5    
  notification:
     runs-on: ubuntu-latest
     needs: build
     if: ${{ needs.build.result == 'failure' || failure() }}
     steps:
       - name: notify
         run: |
           echo "Build step got failed"
           sleep 10  
  deploy:
     runs-on: ubuntu-latest
     if: ${{ always () }}
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 5
     needs: [test, test2]

     
     
     
     
